### ISSUE TITLE
[BUG] Calculator, predicted level too high 

### ISSUE THREAD

**Issue by tdameros** [Sylrelo/42Tools#1]
**Describe the bug**

In the "calculator" page, the calculations regarding level advancements are incorrect. The displayed XP is correct, but the future level shown is significantly **too high**.

**Screenshots**

Here are some screenshots for comparison with 42 evaluator.

<img width="1304" alt="Screenshot 2024-03-19 at 23 13 47" src="https://github.com/Sylrelo/42Tools/assets/50496792/0c490d40-4a23-4ca8-9ef5-f2c5431ccfca">
<img width="1428" alt="Screenshot 2024-03-19 at 23 15 03" src="https://github.com/Sylrelo/42Tools/assets/50496792/e7cb38ab-811b-425f-b96f-aae8b1b0e414">

**Comment by Sylrelo** [comment]
Fixed, I had a forgotten `+1` in the calculation !

<img width="686" alt="image" src="https://github.com/Sylrelo/42Tools/assets/21089555/6c328108-ca1c-45f2-8ce5-21e19ead1ed0">
