### ISSUE TITLE
[BUG] Startup Internship

### ISSUE THREAD

**Issue by damien-vergobbi** [Sylrelo/42Tools#12]
La validation du Startup Internship n'est pas comptée sans l'onglet "My RNCP".

PS : Le Bocal m'a dit qu'il y a deux projets "Startup Internship" dont un masqué.

![image](https://github.com/Sylrelo/42Tools/assets/93730257/9656eb43-6be9-432b-ad03-88577ee448b5)
![image](https://github.com/Sylrelo/42Tools/assets/93730257/e70dfd7b-2915-4e3e-9269-0d8d5f1c8f90)

**Comment by Sylrelo** [comment]
En effet, je ne les avais pas mis dans la liste !

J'ajoute ça et je deploy dans quelques minutes :)

**Comment by Sylrelo** [comment]
Ça devrait te le mettre à jour automatiquement d'ici demain, sinon tu peux forcer l'update via le nouveau bouton ;)

**Comment by damien-vergobbi** [comment]
Super, merci beaucoup !

Le dim. 30 juin 2024 à 14:37, Sylvain Lopez ***@***.***> a
écrit :
