### ISSUE TITLE
[BUG] Impossible de mettre plus de 125 jours sur les internship, startup internship, etc.

### ISSUE THREAD

**Issue by SimonCROS** [Sylrelo/42Tools#18]
**Describe the bug**
Le compteur passe à 125 dès lors que le nombre est plus grand que 125, alors que les stages peuvent durer plus que 125 jours.
Si 125 correspond à la note représentant la durée et non la durée, il faudrait changer le titre du champ qui est actuellement
> Total open-days during contract

**Comment by Sylrelo** [comment]
Bien vu, dans ma folie de lock tous les champs à 125 max j'ai mis celui-ci aussi alors qu'il devrait pas l'être !
