### ISSUE TITLE
[BUG] Les champs progression, level et events dans la section RNCP sont à zéro

### ISSUE THREAD

**Issue by SimonCROS** [Sylrelo/42Tools#2]
**Describe the bug**
Sur ma page RNCP, tous les champs concernant les points globaux pour les RNCP sont à zéro.

**Screenshots**
![image](https://github.com/Sylrelo/42Tools/assets/52134884/9d46bef8-47e5-4fec-9680-d096b5f4b036)

**Additional context**
N/A

**Comment by Sylrelo** [comment]
Il fallait le temps que le serveur update les progressions RNCP de chaque stud, it's good now !

<img width="1169" alt="image" src="https://github.com/Sylrelo/42Tools/assets/21089555/d24df814-15c4-4510-a06f-1ddfb63496e3">
