### ISSUE TITLE
.ZIP cursus, NOT INCLUDED

### ISSUE THREAD

**Issue by hitchhikergalactic** [Sylrelo/42Tools#23]
I hope this message finds you well. My  login is osredond. I am writing to request that my scores please  be reflected  on the website.

 There is a new cursus called  42 .ZIP in Madrid and at the Urduliz campus within Spain, imported from Paris, and we would love to participate in 42 tools However, the issue with my scores not being displayed makes me feel excluded from the Network.

I greatly appreciate the hard work and dedication that goes into maintaining the website and managing these github. Your efforts are highly valued.

Please let me know if there is any additional information needed from my end to resolve this issue. I look forward to your response.
many thanks

**Comment by Sylrelo** [comment]
Hello !

Firstly, I'm sorry it makes you feel that way.
Your level is not being displayed because I only target 42Cursus, at least for now.

~~It's the first time I hear about 42.ZIP, what is the purpose of this cursus ?~~
~~Is it supposed to be a fast/condensed common-core alternative ?~~ 
Edit : After talking to other people, I know what was the "equivalent" cursus in my campus !

I will make changes to save other cursuses to the database, and a new filter client side, I can't give you a precise ETA, it's either for this week-end or the next !

**Comment by hitchhikergalactic** [comment]
Hi,

Firstly, I apologize if my message made you feel bad, that was not my intention, It is not your fault if 42.ZIP students in Spain feel like second-class students, I was having a bad day, and I am grateful for your effort to help.

To answer your questions:
- 42.ZIP is a program for people over 45 years old, in France is run by Pôle Emploi, so a complete success!
- It is supposed to be a fast/condensed alternative to the common core, like a tapas course compared to the common core, which would be the main course, without the option for a freeze, an RNCP, and at the end of the course we don't get to become Alumni, we are just send back home.

For your information, my estimated time of completion (ETEC) is March 12th 2025, my login is osredond

Thank you again for your support!

Best regards,
Os

**Comment by Sylrelo** [comment]
Hey,

Don't worry, it's all good !

So, 42Tools now aggregates all cursus of all users _(well, it will for all active students at the next scheduled update)_.

A filter has been added, that is normaly pre-selected with the current active cursus.
<img width="422" alt="image" src="https://github.com/Sylrelo/42Tools/assets/21089555/3ce0c7bc-5073-4a09-b5a8-06e3fece34d1">

The next update update of your profile should add the new cursus to the list.
If it does not appear this by the end of the week, something's wrong and I will check it out !

**Comment by hitchhikergalactic** [comment]
I wanted to express my heartfelt gratitude for taking the time to assist me, Your kindness has truly lifted my spirits, I am deeply thankful for your support and the efforts you've made on my behalf.
I will review my profile over the weekend, and if it does not appear in the main course list for Madrid, I will inform you on Monday.
Many, many thanks once again for your generosity and encouragement.
Warmest regards,
OSmani
