### ISSUE TITLE
[BUG] XP Number displayed needs to be rounded to fewer decimals

### ISSUE THREAD

**Issue by cpaluszek** [Sylrelo/42Tools#26]
**Describe the bug**
The number displayed (1485.0000000000002 XP) contains too many decimal places, which negatively impacts the user interface.

**Screenshots**
![image](https://github.com/Sylrelo/42Tools/assets/105011036/0edbb048-cc7d-47d6-aa13-8bd2b022b7dc)

**Comment by Sylrelo** [comment]
Oops, nice catch ! I think that's the only place I forgot to fix it 
Will deploy tomorrow !
