### ISSUE TITLE
[BUG] Le nombre d'events et d'expériences devraient être affiché sans virgule

### ISSUE THREAD

**Issue by SimonCROS** [Sylrelo/42Tools#29]
**Describe the bug**
Le nombre d'events ne peut pas avoir de partie décimale, il est donc inutile de l'afficher.

**Screenshots**
<img width="828" alt="image" src="https://github.com/user-attachments/assets/f868604a-bd54-4559-8c14-6cf654c2e59d">

**Additional context**
D'ailleurs, est-il nécessaire de bloquer quand le quota est atteint ? (Par exemple afficher `Events: 20/10` avec la barre verte)

**Comment by Sylrelo** [comment]
Holà,

Pour le quota bloqué, c'est parce que je me base sur mon "cache" RNCP qui calcule les pourcentages globaux, dans ce contexte la, oui je dois bloquer.

Par contre je peux à la rigueur changer la récupération côté front juste pour ces informations la (il me semble l'avoir déjà débloqué pour le level lors du dernier deploy)
