### ISSUE TITLE
[Feature] Bouton reset du zoom du graphique du calculateur

### ISSUE THREAD

**Issue by SimonCROS** [Sylrelo/42Tools#30]
**Describe the solution you'd like**
Actuellement, quand on réalise une sélection sur le graphique du calculateur (cela zoom sur cette zone), il est complexe voir quasi impossible de revenir à l'affichage complet. Il faudrait ajouter un bouton `reset` à côté de "Graph".

**Additional context**
Est-ce que cette feature du zoom est vraiment intéressante ? Faudrait-il plutôt peut-être juste la désactiver ?

**Comment by Sylrelo** [comment]
Holà,

C'est en effet le comportement par défaut de la lib de graphe que j'avais utilisé, je vais désactiver le zoom 😉
