### ISSUE TITLE
[Feature] Les alumnis ne sont pas représentés différemment.

### ISSUE THREAD

**Issue by SimonCROS** [Sylrelo/42Tools#32]
**Describe the solution you'd like**
Sur 42evaluators, les alumnis étaient avec un background orange, sur 42tools il n'y a plus d'indicateur si la personne est alumni (peut-être griser et mettre un tag ?)

**Comment by Sylrelo** [comment]
Holà,

Je pense que je vais mettre un petit tag à côté (comme pour les tag du campus / années), et assombrir les couleurs
