### ISSUE TITLE
[BUG] Impossible de se connecter

### ISSUE THREAD

**Issue by SimonCROS** [Sylrelo/42Tools#39]
**Describe the bug**
Ça redirige plusieurs fois avant de voir brièvement une erreur 401 puis redirige sur la page de login.

**Comment by Sylrelo** [comment]
Yes je m'en suis aperçu hier soir, normalement c'est partiellement fix !
La moindre erreur du back forçait une déconnection totale du front, j'ai changé ça, du coup devrait plus déconnecter.

C'est les stats Transcendance qui provoquent des erreurs 500, faut que je m'en occupe dans les jours qui viennent !
