### ISSUE TITLE
[BUG] kfs-7 is missing

### ISSUE THREAD

**Issue by hijkl2e** [Sylrelo/42Tools#54]
**Describe the bug**
In RNCP progression, there are two kfs-6 and no kfs-7.

**Screenshots**
![Screenshot_20241019_061927_Chrome](https://github.com/user-attachments/assets/2afafca7-1abf-45e2-8afb-47df27e2bd29)

**Additional context**

**Comment by Sylrelo** [comment]
Good catch !
It's fixed, but I need to re-trigger an update of the RNCP progress (soon)
