### ISSUE TITLE
Black hole days in calculator[Feature]

### ISSUE THREAD

**Issue by ayan479** [Sylrelo/42Tools#7]
It would be really nice if the Calculator showed the amount of BH days to be received from completion of project alongside the exp.

**Comment by Sylrelo** [comment]
Hey, sorry for the late reply.

I'm sorry, but I won't implement this feature : 
- I can't access the necessary data to calculate the gained days
- Highly discouraged by a member of my campus staff, as it would kind of ruin the interest of the pace system
