### ISSUE TITLE
[BUG] Projet rendu il y a 3 semaines est toujours compté comme pas fait

### ISSUE THREAD

**Issue by rkowalsk** [Sylrelo/42Tools#9]
**Describe the bug**
J'ai rendu override il y a 25 jours et il est toujours en rouge dans "My RNCP" et mon XP n'est pas bon, il manque l'XP donnée par le projet en question.

**Screenshots**
![Capture d’écran du 2024-06-24 12-12-01](https://github.com/Sylrelo/42Tools/assets/43633272/e3f2e5ca-0b6f-4d84-99b8-3d157ce7e889)
![Capture d’écran du 2024-06-24 11-57-49](https://github.com/Sylrelo/42Tools/assets/43633272/89216ec6-4d88-4a94-bb86-22bf91d75151)
![Capture d’écran du 2024-06-24 12-03-41](https://github.com/Sylrelo/42Tools/assets/43633272/f2694426-c888-46b8-8fc9-93850fd30b4c)
![Capture d’écran du 2024-06-24 12-02-53](https://github.com/Sylrelo/42Tools/assets/43633272/54b3f964-7f67-4a48-8535-c8186c6e5cb7)

**Additional context**
J'ai checké le site peu de temps après avoir rendu le projet, rechecké il y a quelques jours et encore une fois aujourd'hui pour voir si ça avait changé mais non.

**Comment by Sylrelo** [comment]
Je note, je regarde ça ce week-end !

**Comment by Sylrelo** [comment]
J'ai rajouté un bouton pour forcer l'update (projets et level) dans la prochaine update.
Tu me dira ce que ça donne ;)
